personal_site/personal_site/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from website import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^', include('website.urls',namespace='website')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_site/website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^portfolio/$', views.portfolio, name="developer"),
    url(r'^about/$', views.about, name="about"),
    url(r'^gallery/$', views.gallery, name="gallery"),
    url(r'^blog/$', views.blog, name="blog"),
    url(r'^blog/(?P<slug>[-\w]+)$', views.detail, name="detail"),
    url(r'^search/(?P<topic>[\w\-]+)/$', views.search_blog_by_tag, name='search'),
]

personal_site/website/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.template.defaultfilters import slugify
from markdownx.models import MarkdownxField

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    category = ArrayField(models.CharField(max_length=50),blank=True,null=True)
    content = MarkdownxField()
    image = models.FileField(blank=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

class Project(models.Model):
    field = models.CharField(max_length=50,default='data science')
    title = models.CharField(max_length=100)
    topics = ArrayField(models.CharField(max_length=50),blank=True,null=True)
    content = models.TextField(max_length=1000)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    github_link = models.CharField(max_length=100,blank=True,null=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Project, self).save(*args, **kwargs)

personal_site/website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Project
from django.db.models import Q
from itertools import chain

# Create your views here.
def index(request):
    return render(request, 'web/index.html')

def about(request):
    return render(request, 'web/about.html')

def gallery(request):
    return render(request, 'web/gallery.html')

def blog(request):
    # hike_posts = Post.objects.filter(Q(category__icontains='hike'))
    # camp_posts = Post.objects.filter(Q(category__icontains='camp'))
    # code_posts = Post.objects.filter(Q(category__icontains='code'))
    all_posts = Post.objects.all()
    return render(request, 'web/blog.html', {'all_posts':all_posts})

def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'web/detail.html', {'post':post})

def portfolio(request):
    all_ds_projects = Project.objects.filter(field="data science")
    all_fs_projects = Project.objects.filter(field="full stack")
    return render(request, 'web/portfolio.html',{
                                                'all_ds_projects':all_ds_projects,
                                                'all_fs_projects':all_fs_projects
                                                })


def search_blog_by_tag(request, topic):
    related_posts = Post.objects.filter(Q(category__icontains=topic)).distinct().order_by('-id')
    related_projects = Project.objects.filter(Q(topics__icontains=topic)).distinct().order_by('-id')
    all_related = list(chain(related_posts,related_projects))
    return render(request, 'web/search.html', {'all': all_related, 'result': topic})

personal_site/website/templates/web/about.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" href="{% static 'web/css/style.css' %}">

    <section class="intro">

      <header class="about-header">
        <h1>About Troy Kayne</h1>

        <a class="discover" href="#About">
          <i class="fa fa-angle-double-down"></i>
        </a>

      </header>

    </section>

    <section class="About" id="About">
      <nav class="navbar navbar-default" id="cd-main-nav">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="{% static 'web/img/logo.png' %}" width="50" alt=""></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-center">
                <li><a href="/portfolio">Portfolio</a></li>
                <li><a href="/gallery">Gallery</a></li>
                <li><a href="/blog">Blog</a></li>
                <li><a href="/about">About</a></li>
              </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <div class="About-wrapper">
        <section id="story" class="story">
          <div class="story-thumbnail">
            <img src="{% static 'web/img/me.jpg' %}" width="400" alt="picture of me" />
          </div>
          <div class="story-p">
            <div class="social">
              <div class="links">
                <a href="https://www.linkedin.com/in/troykayne/" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                <a href="https://github.com/kayne10" target="_blank"><i class="fa fa-github-square" aria-hidden="true"></i></a>
                <a href="https://twitter.com/tkayne403" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <!-- <a href="http://creative.colorado.edu/~trka2035/Projects/2/Portfolio/"><img src="/images/ath_ralphie.png" height="50px" alt="" /></a> -->
              </div>
            </div>
            <h3>Computer Science at University of Colorado Boulder</h3>
            <p>
              I graduated from University of Colorado Boulder in the Spring of 2018.
              As a Computer Science major, I engaged in software development classes such as Algortihms, Operating Systems, and
              Big Data Architecture. I have a passion for Web Development and Deep/Machine learning.
            </p>
            <h3>Data Science at Galvanize</h3>
            <p>
              Afer graduating from the University of Colorado Boulder, I wanted to continue my education by pursuing a
              15 week Data Science Immersive Program at Galvanaize in Denver, CO. This program was a Python-based curriculum
              focused on machine learning, statistical analysis and big data. I came out with a huge background in machine learning
              and statistical analysis where I strongly developed data visualization skills as well. In addition to participating
              in many case studies and projects, I spent my last two intense weeks focused on my capstone project that consisted
              of a beer recommendation system and convolutional neural network classifying on beer style.
            <h3>Full Stack Web Developing</h3>
            <p>
              After completing web development courses and projects on the side of all my studies, I am offering freelancing services for anyone interesting in needing a website.
              These services target anyone such as Skiers, Restaraunt Managers, Public Announcements, and other freelancers with a business.
              The number of pages is not an issue, I develope static and dynamic websites that suits any desired requirements. Sometimes, Front-End development
              can get boring to me, so I started to focus on best strategies for Back-End/Full-Stack development. My favorite frameworks are Django/Flask, Node/Express, and Rails.
            </p>
            <h3>Photography and Exploring</h3>
            <p>
              Boulder, Colorado is an amazing place to see. I love exploring the mountains, and I love bringing my camera with me, too.
              Boulder has so many exotic places to explore. Those beautiful sunrises and sunsets keeps me inspired to be a photographer.
            </p>
            <!-- <p>Also, check out my freelance services at <strong class="freelance-site"><a href="https://remote.com/troykayne">remote.com</a></strong>!</p> -->
          </div>
        </section>

          <section class="skills-wrapper" id="skills">
            <div class="row skill-container">
              <h3>Tech Skills</h3>
              <div class="col-sm-3">
                <h5>Data Science/Machine Learning</h5>
                <ul>
                  <li data-score="3">SKlearn</li>
                  <li data-score="2">Keras</li>
                  <li data-score="2">Tensorflow</li>
                  <li data-score="4">Pandas</li>
                  <li data-score="4">Numpy</li>
                </ul>
              </div>
              <div class="col-sm-3">
                <h5>Data Engineering</h5>
                <ul>
                  <li data-score="4">Data warehouse</li>
                  <li data-score="4">Data lake</li>
                  <li data-score="4">ETL</li>
                  <li data-score="3">Pyspark</li>
                  <li data-score="3">Airflow</li>
                </ul>
              </div>
              <div class="col-sm-3">
                <h5>DevOps Skills</h5>
                <ul>
                  <li data-score="4">AWS</li>
                  <li data-score="4">Digital Ocean</li>
                  <li data-score="4">Docker</li>
                  <li data-score="2">Jenkins</li>
                </ul>
              </div>
            </div>
            <div class="row skill-container">
              <div class="col-sm-3">
                <h5>Front-End Skills</h5>
                <ul>
                  <li data-score="4">HTML5
                  </li>
                  <li data-score="4">CSS3
                  </li>
                  <li data-score="4">JavaScript
                  </li>
                  <li data-score="3">React/Redux
                  </li>
                </ul>
              </div>
              <div class="col-sm-3">
                <h5>Back-End Skills</h5>
                <ul>
                  <li data-score="4">SQL & MongoDB
                  </li>
                  <li data-score="4">Django/Flask
                  </li>
                  <li data-score="3">Ruby on Rails
                  </li>
                  <li data-score="3">Node/Express.js
                  </li>
                </ul>
              </div>
              <div class="col-sm-3">
                <h5>Full-Stack Skills</h5>
                <ul>
                  <li data-score="4">LEMP</li>
                  <li data-score="3">MERN</li>
                </ul>
              </div>
              <div class="col-sm-3">
                <h5>Photography Skills</h5>
                <ul>
                  <li data-score="3">Adobe Photoshop</li>
                  <li data-score="4">Adobe Bridge</li>
                </ul>
              </div>
            </div>
          </section>

        </div>
    </section>
{% endblock %}

personal_site/website/templates/web/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Engineer and Photographer">
    <meta name="author" content="Troy Kayne">
    <meta property="og:image" content="http://troykaynedesignandphoto.com/static/web/img/blackLogo.png">
    <title>Troy Kayne - Software | Photography | Adventure</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'web/img/favicon.ico'%}"/>
    <link href="https://fonts.googleapis.com/css?family=Pathway+Gothic+One|Poiret+One" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="{% static 'web/style.css' %}" /> -->
    <link rel="stylesheet" href="/static/web/css/intro.css">
    <link rel="stylesheet" href="/static/web/css/SyntaxHighlighter.css">

    <!-- jQuery is required for Bootsrtap JS -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Share this scripts -->
    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" id="st_insights_js" src="http://w.sharethis.com/button/buttons.js?publisher=37361ad7-20a5-4bd8-8f47-e2f48ef59fd4"></script>
    <script type="text/javascript">stLight.options({publisher: "37361ad7-20a5-4bd8-8f47-e2f48ef59fd4", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  </head>
  <body>
     <!-- Navbar -->


    {% block body %}
    {% endblock %}

    <!-- Footer -->
    <footer id="footer">
      <p class="copyright">&copy;2017 troykaynedesignandphoto.com.</p>
      <center>
        <div class="footer-links">
          <a href="https://www.linkedin.com/in/troykayne/" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
          <a href="https://github.com/kayne10" target="_blank"><i class="fa fa-github-square" aria-hidden="true"></i></a>
          <a href="https://twitter.com/tkayne403" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          <!-- <a href="http://creative.colorado.edu/~trka2035/Projects/2/Portfolio/"><img src="/images/ath_ralphie.png" height="50px" alt="" /></a> -->
        </div>
      </center>
    </footer>

    <!-- Bootstrap JS -->
    <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="/static/web/js/main.js"></script>
    <script type="text/javascript" src="/static/web/js/shCore.js"></script>
    <script type="text/javascript" src="/static/web/js/shBrushPython.js"></script>
    <script class="javascript">
      // dp.SyntaxHighlighter.ClipboardSwf = 'Scripts/clipboard.swf';
      dp.SyntaxHighlighter.HighlightAll('code');
      </script>
  </body>
</html>

personal_site/website/templates/web/blog.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}
<link rel='stylesheet' href='{% static 'web/css/style.css' %}' />

<section class="intro">

  <header class="explore-header">
    <h1>Blog & Creatives</h1>

    <a class="discover" href="#explore">
      <i class="fa fa-angle-double-down"></i>
    </a>

  </header>

</section>

<section class="explore-page" id="explore">
  <nav class="navbar navbar-default" id="cd-main-nav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><img src="{% static 'web/img/logo.png' %}" width="50" alt=""></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-center">
            <li><a href="/portfolio">Portfolio</a></li>
            <li><a href="/gallery">Gallery</a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/about">About</a></li>
          </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


</section>

<div class="blog-wrapper">
  <br>
  <div class="row blog-row">
    <div class="hike-container">
      {% if all_posts %}
        {% for post in all_posts %}
          <a href="{% url 'website:detail' post.slug %}">
            <div class="col-md-4 post-thumbnail">
              {% if post.image %}
                <img src="{{ post.image.url }}" alt="" class="img-responsive">
              {% else %}
                <img src="/static/web/img/Logo.png" class="img-responsive" alt="">
              {% endif %}
              <div class="caption">
                <h3>{{ post.title|title }}</h3>
                <ul>
                  {% for topic in post.category %}
                    <li class="badge badge-default">{{ topic }}</li>
                  {% endfor %}
                </ul>
                <p>
                  Click for more
                </p>
                <!-- sharing options -->
                <div class="share">
                  <span class='st_facebook_large' displayText='Facebook'></span>
                  <span class='st_twitter_large' displayText='Tweet'></span>
                </div>
              </div>
            </div>
          </a>
        {% endfor %}
      {% else %}
        <h3>No Posts at the moment...</h3>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

personal_site/website/templates/web/detail.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}
<link rel='stylesheet' href='{% static 'web/css/style.css' %}' />

<nav class="navbar navbar-default" id="cd-main-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="{% static 'web/img/logo.png' %}" width="50" alt=""></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-center">
          <li><a href="/portfolio">Portfolio</a></li>
          <li><a href="/gallery">Gallery</a></li>
          <li><a href="/blog">Blog</a></li>
          <li><a href="/about">About</a></li>
          <!-- <li><a href="/contact">Contact</a></li> -->
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="post-view">
  {% if post.image %}
    <img src="{{ post.image.url }}" alt="" class="img-responsive">
  {% endif %}
  <h2>{{ post.title }}</h2>
  <div class="caption">
    <ul>
      {% for topic in post.category %}
        <a href="{% url 'website:search' topic %}"><li class="badge badge-default">{{ topic }}</li></a>
      {% endfor %}
    </ul>
    {{ post.content|safe }}
  </div>
  <!-- sharing options -->
    <div class="share">
      <span class='st_facebook_large' displayText='Facebook'></span>
      <span class='st_twitter_large' displayText='Tweet'></span>
    </div>
</div>

{% endblock %}

personal_site/website/templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}
  <div class="intro">
    <ul class="cb-slideshow">
        <li><span>Image 01</span></li>
        <li><span>Image 01</span></li>
        <li><span>Image 01</span></li>
        <li><span>Image 01</span></li>
        <li><span>Image 01</span></li>
        <li><span>Image 01</span></li>
    </ul>

    <!-- Header -->
      <header id="header">
        <div class="logo">
          <span class="icon"></span>
        </div>
        <div class="content">
          <div class="inner">
            <h1>Troy Kayne</h1>
            <p>Software | Photography | Adventure</p>
          </div>
        </div>
        <nav>
          <ul>
            <li><a href="/portfolio">Portfolio</a></li>
            <li><a href="/gallery">Gallery</a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/about">About</a></li>
            <!-- <li><a href="/contact">Contact</a></li> -->
          </ul>
        </nav>
      </header>
  </div>
{% endblock %}

personal_site/website/templates/web/portfolio.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}
<link rel='stylesheet' href='{% static 'web/css/style.css' %}' />

<section class="intro">

  <header class="products-header">
    <h1>Code Portfolio</h1>

    <a class="discover" href="#ds-projects">
      <i class="fa fa-angle-double-down"></i>
    </a>

  </header>

</section>

<section class="packages" id="ds-projects">
  <nav class="navbar navbar-default" id="cd-main-nav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><img src="{% static 'web/img/logo.png' %}" width="50" alt=""></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-center">
            <li><a href="/portfolio">Portfolio</a></li>
            <li><a href="/gallery">Gallery</a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/about">About</a></li>
            <!-- <li><a href="/contact">Contact</a></li> -->
          </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="products-templates">
    <h1>Data Science</h1>
    <div class="ds-wrapper">
        <!-- Data Science Projects -->
        <div class="ds-heading">
          <h1>Projects</h1>
        </div>
        <hr>
        {% if all_ds_projects %}
        {% for project in all_ds_projects %}
          <div class="row">
            <div class="col-md-9">
              <h2>{{ project.title }}</h2>
              <h4>{{ project.content }}</h4>
            </div>
            <div class="col-md-3">
              <div class="well">
                {% if project.github_link %}
                <span>
                  <a href="{{project.github_link}}" target="_blank">Link <i class="fa fa-github-square" aria-hidden="true"></i></a>
                </span>
                {% else %}
                <span>
                  No Link :(
                </span>
                {% endif %}
                <h4>Topics: </h4>
                <span>
                  <ul>
                    {% for topic in project.topics %}
                    <a href="{% url 'website:search' topic %}"><li class="badge badge-default">{{topic}}</li></a>
                    {% endfor %}
                  </ul>
                </span>
              </div>
            </div>
          </div>
        {% endfor %}
        {% else %}
          <h3>No projects listed yet...</h3>
        {% endif %}
        <!-- <div class="row">
          <div class="col-md-9">
            <h2>Data Analytics and Behind-the-scenes of Spotify</h2>
            <h4>Spotify is a great digital music service and I recommend this media application as your primary choice for listening to music.
            In this project, I look at the data metrics that play a huge role in Spotify's machine learning program.  I hope you can see why Spotify
          is a fantastic service that generates great music suggestions for all its users.</h4>
          </div>
          <div class="col-md-3">
            <div class="well">
              <span><a href="https://kayne10.github.io/data-science-blog/jnotebooks/SpotifyNotebook.html">Link <i class="fa fa-external-link" aria-hidden="true"></i></a></span>
              <h4>Topics: </h4><span>Python, Jupyter Notebook, Pandas, Data Visualization</span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-9">
            <h2>Discoveries of Cryptocurrencies</h2>
            <h4>In this project, I am motivated by exploring how Bitcoin correlates with both other cryptocurrencies and other physical currencies/stocks is important for investors and
              general consumer interest.  By exploring how related Bitcoin is I can determine its quality as an independent investment or if it will
              rise and fall with other cryptocurrency investments.</h4>
          </div>
          <div class="col-md-3">
            <div class="well">
              <span><a href="https://kayne10.github.io/data-science-blog/jnotebooks/CC_Analytics.html">Link <i class="fa fa-external-link" aria-hidden="true"></i></a></span>
              <h4>Topics: </h4><span>Python, Jupyter Notebook, Pandas, Data Visualization</span>
            </div>
          </div>
        </div> -->
      </div>
    </div>
</section>

<section class="products" id="fs-projects">
  <div class="products-templates">
    <h1>Full Stack Web Development</h1>
    <div class="ds-wrapper">
        <!-- Data Science Projects -->
        <div class="ds-heading">
          <h1>Projects</h1>
        </div>
        <hr>
        {% if all_fs_projects %}
          {% for project in all_fs_projects %}
            <div class="row">
              <div class="col-md-9">
                <h2>{{ project.title }}</h2>
                <h4>{{ project.content }}</h4>
              </div>
              <div class="col-md-3">
                <div class="well">
                  {% if project.github_link %}
                  <span>
                    <a href="{{project.github_link}}" target="_blank">Link <i class="fa fa-github-square" aria-hidden="true"></i></a>
                  </span>
                  {% else %}
                  <span>
                    No Link :(
                  </span>
                  {% endif %}
                  <h4>Topics: </h4>
                  <span>
                    <ul>
                      {% for topic in project.topics %}
                        <a href="{% url 'website:search' topic %}"><li class="badge badge-default">{{topic}}</li></a>
                      {% endfor %}
                    </ul>
                  </span>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h3>No projects listed yet...</h3>
        {% endif %}
      </div>
    </div>
</section>

<!-- <h1>Contact Me With A Website Idea</h1>
<h3>Pick the Freelance package that best suits your need </h3>
<center><a href="#ds-projects"><button type="button" class="custom-btn">Skip to Data Science</button><a href="/contact"><button type="button" class="custom-btn">Contact Me</button></a></a></center>
<div class="package-wrapper">
  <div class="col-md-4">
    <h3 class="package-header">Front-End Development</h3>
    <div class="caption">
      <p>
        Charge Rate: $20/hr
      </p>
      <ul>
        <li>Static Website</li>
        <li>Personal Landing Page</li>
        <li>Personal Portfolio</li>
        <li>Responsive</li>
        <li>HTML, CSS, and Javascript</li>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <h3 class="package-header">API Development</h3>
    <div class="caption">
      <p>
        Charge Rate: $25/hr
      </p>
      <ul>
        <li>Express, Django, or Rails</li>
        <li>User Authentication</li>
        <li>RESTful API</li>
        <li>SQL/NoSQL</li>
        <li>AWS, Digital Ocean, or Heroku</li>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <h3 class="package-header">Full Stack Development</h3>
    <div class="caption">
      <p>
        Charge Rate: $30/hr
      </p>
      <ul>
        <li>Responsive</li>
        <li>User Authentication</li>
        <li>Admin Panel</li>
        <li>Merchandise & E-commerce</li>
        <li>Express, Django, or Rails</li>
        <li>RESTful API</li>
        <li>SQL/NoSQL</li>
        <li>AWS, Digital Ocean, or Heroku</li>
        <li>Scalable Services with Docker</li>
      </ul>
    </div>
  </div>
</div> -->

{% endblock %}